### ISSUE TITLE
Change branch meanings to better fit review process

### ISSUE THREAD

**Issue by pmac** [mozmeao/www-admin#17]
After a discussion with the team we've discovered a disconnect between how this repo works and how code and content reviews really work. The primary issue is the desire for changes to be on dev before code review so that content review can happen with the non-developer stakeholders. I therefore propose that we change branch meanings as follows:

* Create a `dev` branch that will map to www-dev.allizom.org. Developers will push to this branch before formal code-review to allow the dev server to be a platform for content review for stakeholders.
* Delete the `stage` branch
* Have the `master` branch map to the staging server, www.allizom.org
* Keep the `prod` branch unchanged, but moving changes to prod would mean moving from `master` to `prod`, rather than having the `stage` branch be a separate step.

So the proposed publishing process will be:

1. Push changes directly to the `dev` branch and have the requesting partner review on www-dev.allizom.org.
2. Submit a PR from `dev` to `master` and have a team-member review the code changes if desired. Code reviews aren't strictly required here since a successful dev deployment in step 1 means that it's working.
3. Once PRs merge to `master` this will update our staging server, www.allizom.org
4. Once things pass final approval on staging and we're ready to update production, it will simply be `git checkout master; git pull origin; git push origin master:prod`.

**Comment by jpetto** [comment]
Is there a reason that the existing demo system isn't sufficient for showing work to non-dev stakeholders?

**Comment by pmac** [comment]
@jpetto the basic answer is that the dev team needs to get changes to these cards up on www-dev before code review. They'd like to mostly keep code review however, and as all other projects do code review on PRs against `master` they'd like to keep that for this as well. So we're moving to a pre-PR `dev` branch model, and then PR and code-review after that for `master` branch, and then the same `git push origin master:prod` for getting changes to prod.

**Comment by jpetto** [comment]
Not against the new model at all, but why can't the existing `demo/whatever` branch/deploy system work here? Is it something to do with the content cards?
